general {
    lock_cmd = pidof hyprlock || hyprlock

    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on && brightnessctl -r

    # ignore_dbus_inhibit = true
    # ignore_systemd_inhibit = true
    # ignore_wayland_inhibit = true
    inhibit_sleep = 3
}

listener {
    timeout = 300
    on-timeout = idle.sh dim in
    on-resume = idle.sh dim
}

listener {
    timeout = 330
    on-timeout = idle.sh lock in
    on-resume = idle.sh lock
}

listener {
    timeout = 600
    on-timeout = idle.sh off in
    on-resume = idle.sh off
}

listener {
    timeout = 900
    on-timeout = idle.sh sleep in
    on-resume = idle.sh sleep
}
