-- vim.api.nvim_create_autocmd("VimEnter", {
--   group = vim.api.nvim_create_augroup("uLspLocalConfigs", { clear = true }),
--   once = true,
--   callback = function()
--     local configs = "_nvim"
--     local root = vim.fn.getcwd() .. "/"
--     if vim.fn.isdirectory(root .. configs) == 1 then
--       local files = vim.fn.readdir(root .. configs)
--       for _, file in ipairs(files) do
--         local lsp = file:match("(.+)%.lua$")
--         if lsp then
--           local config = require(configs .. "." .. lsp)
--           if config then
--             vim.lsp.config(lsp, config)
--           end
--         end
--       end
--     end
--   end,
-- })

-- local function scratch()
--   local buf = vim.api.nvim_create_buf(false, false)
--   vim.bo[buf].buftype = "nofile"
--   vim.bo[buf].bufhidden = "hide"
--   vim.bo[buf].swapfile = false
--   vim.bo[buf].filetype = "lua"
--   vim.api.nvim_set_current_buf(buf)
-- end
--
-- vim.keymap.set("n", "<leader>Y", scratch, { desc = "Scratch" })

-- vim.lsp.config('jsonls', {
-- 	name = "jsonls",
-- 	cmd = { 'vscode-json-language-server', '--stdio' },
-- 	filetypes = { 'json', 'jsonc' },
-- 	init_options = {
-- 		provideFormatter = true,
-- 	},
-- 	root_markers = { '.git' },
-- })
-- vim.lsp.enable({ "jsonls" })
