return {
  "nvim-treesitter/nvim-treesitter",
  branch = "main",
  build = ":TSUpdate",
  lazy = false,
  config = function()
    require("nvim-treesitter").install({
      "bash",
      "c",
      "comment",
      "css",
      "csv",
      "diff",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitignore",
      "html",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "rust",
      "toml",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
      "latex",
      "ebnf",
    })
  end,
}
